"""empty message

Revision ID: 1422d04296b6
Revises: 2fa2ebe29be5
Create Date: 2014-03-05 15:51:44.197163

"""

# revision identifiers, used by Alembic.
revision = '1422d04296b6'
down_revision = '2fa2ebe29be5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('invest_total', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'invest_total')
    ### end Alembic commands ###
