"""empty message

Revision ID: 1ad9e39b31d7
Revises: 4db5c8b20c9
Create Date: 2014-03-05 11:41:34.107392

"""

# revision identifiers, used by Alembic.
revision = '1ad9e39b31d7'
down_revision = '4db5c8b20c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officer', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_index('ix_officer_candidate_id', 'officer', ['candidate_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_officer_candidate_id', table_name='officer')
    op.drop_column('officer', 'candidate_id')
    ### end Alembic commands ###
