"""empty message

Revision ID: 2fa2ebe29be5
Revises: 1ad9e39b31d7
Create Date: 2014-03-05 14:42:54.139863

"""

# revision identifiers, used by Alembic.
revision = '2fa2ebe29be5'
down_revision = '1ad9e39b31d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committee', sa.Column('type', sa.String(length=25), nullable=True))
    op.create_index('ix_committee_type', 'committee', ['type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_committee_type', table_name='committee')
    op.drop_column('committee', 'type')
    ### end Alembic commands ###
