"""empty message

Revision ID: 4db5c8b20c9
Revises: None
Create Date: 2014-03-04 14:41:23.034157

"""

# revision identifiers, used by Alembic.
revision = '4db5c8b20c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_officer_committee_id', 'officer', ['committee_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_officer_committee_id', table_name='officer')
    op.drop_table('officer')
    ### end Alembic commands ###
