"""empty message

Revision ID: 520f68a6684a
Revises: 1422d04296b6
Create Date: 2014-03-10 10:03:31.503412

"""

# revision identifiers, used by Alembic.
revision = '520f68a6684a'
down_revision = '1422d04296b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'candidate', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_index('ix_candidate_person_id', 'candidate', ['person_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_person_id', table_name='candidate')
    op.drop_column(u'candidate', 'person_id')
    op.drop_table('person')
    ### end Alembic commands ###
